[build]
  publish = "public/"

[dev]
  port = 3000

[functions]
  directory = "server/"
  included_files = ["./server/**/*.html"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
